# =========================
# Base (applies to ALL profiles)
# =========================
spring:
  application:
    name: claims

  profiles:
    default: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false


---
# =========================
# DEV profile (H2 in-memory + H2 console)
# =========================
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:claimsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console


---
# =========================
# LOCAL profile (Postgres)
# =========================
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/claimsdb
    driver-class-name: org.postgresql.Driver
    username: kevin
    password: kevin
  
  sql:
    init:
      mode: always
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true



---
# =========================
# TEST profile (H2, isolated + recreate schema)
# =========================
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:claimsdb_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true

    
